client:
  - changed-files:
      - any-glob-to-any-file:
          - client/**

server:
  - changed-files:
      - any-glob-to-any-file:
          - server/**

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - "**/*.md"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - client/src/**/*.test.jsx
          - server/test/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
          - client/package.json
          - client/package-lock.json
          - server/package.json
          - server/package-lock.json
